@BASE_URL = http://localhost:8000

# @ping
GET {{BASE_URL}}/ping

###

# @name get_products
GET {{BASE_URL}}/products

###

# @name create_product
POST {{BASE_URL}}/products
Content-Type: application/json

{
  "product_name": "Cachorro-quente",
  "product_price": "100"
}

###

# @name get_product_by_id
GET {{BASE_URL}}/products/3
